version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://admin:123456789@192.168.108.6:27017?authSource=admin
    restart: unless-stopped
