stages:
  preprocess:
    cmd: python src/preprocess.py --input data/raw.csv --output data/processed.csv
    deps:
      - src/preprocess.py
      - data/raw.csv
    outs:
      - data/processed.csv

  train:
    cmd: python src/train.py --data data/processed.csv --model model.pkl
    deps:
      - src/train.py
      - data/processed.csv
    outs:
      - model.pkl
    metrics:
      - metrics.json

  evaluate:
    cmd: python src/evaluate.py --model model.pkl --data data/processed.csv
    deps:
      - src/evaluate.py
      - model.pkl
      - data/processed.csv
    metrics:
      - eval.json
