stages:
  train:
    cmd: python train.py --data data/finetune/
    deps:
      - train.py
      - data/finetune/
    metrics:
      - metrics.json

  evaluate:
    cmd: python test.py --data data/finetune/
    deps:
      - test.py
      - data/finetune/
    metrics:
      - eval.json
