server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Thu thập log hệ thống (syslog)
  - job_name: syslog
    static_configs:
      - targets: [localhost]
        labels:
          job: syslog
          __path__: /var/log/syslog

  # Thu thập log ứng dụng (nếu có file log riêng)
  - job_name: app-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: app-logs
          __path__: /var/log/*.log

  # Thu thập stdout/stderr của container Docker
  - job_name: docker
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log 