global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'fastapi'
    static_configs:
      - targets: ['web:8000']
    metrics_path: '/metrics'
    dns_sd_configs:
      - names:
        - 'web'
        type: 'A'
        port: 8000
